Paclet[
  Name -> "Prototypes",
  Description -> "A paclet for prototype functions",
  Creator -> "Arnoud Buzing",
  Publisher -> "Wolfram Research",
  Version -> "0.1.0",
  MathematicaVersion -> "11.2+",
  Loading -> Automatic,
  Extensions -> {
   { "Documentation", Language -> "English"},
   { "Kernel",
   Symbols -> {
     "Prototypes`InformationDataset",
     "Prototypes`ImportFiles",
     "Prototypes`ImportDirectory",
     "Prototypes`GetFiles",
     "Prototypes`DirectoryByteCount",
     "Prototypes`DirectorySize",
     "Prototypes`ToStringFileName",
     "Prototypes`URLHash",
     "Prototypes`$InputDirectoryName",
     "Prototypes`$ExtensionToFormat",
     "Prototypes`$FormatToExtension",
     "Prototypes`SystemStringOpen",
     "Prototypes`CreateGIFAnimation",
     "Prototypes`UnmatchQ",
     "Prototypes`By",
     "Prototypes`MeanBy",
     "Prototypes`StandardDeviationBy",
     "Prototypes`MedianBy",
     "Prototypes`VarianceBy",
     "Prototypes`CommonestBy",
     "Prototypes`MinBy",
     "Prototypes`MaxBy",
     "Prototypes`RarestBy",
     "Prototypes`Rarest",
     "Prototypes`DatasetMap",
     "Prototypes`DatasetImport",
     "Prototypes`DatasetImportFiles",
     "Prototypes`MakeString",
     "Prototypes`StringFirst",
     "Prototypes`StringLast",
     "Prototypes`StringRest",
     "Prototypes`StringMost",
     "Prototypes`RandomGeoPosition",
     "Prototypes`ImageStrictlyPortraitQ",
     "Prototypes`ImagePortraitQ",
     "Prototypes`ImageStrictlyLandscapeQ",
     "Prototypes`ImageLandscapeQ",
     "Prototypes`ImageSquareQ",
     "Prototypes`Image3DCubeQ",
     "Prototypes`ImageCropResize",
     "Prototypes`AlphaChannelQ",
     "Prototypes`Uniconize",
     "Prototypes`BoxSyntaxQ",
     "Prototypes`PacletInformationDataset",
     "Prototypes`BuildWikiDocumentation",
     "Prototypes`$BuildInfo",
     "Prototypes`BuildInfo",
     "Prototypes`DockButton",
     "Prototypes`$DockButtons",
     "Prototypes`ExpressionServer",
     "Prototypes`ExpressionEvaluate",
     "Prototypes`$LocalResourceObjects",
     "Prototypes`ResourceObjectManager",
     "Prototypes`ResourceObjectDataset",
     "Prototypes`Second",
     "Prototypes`Third",
     "Prototypes`Fourth",
     "Prototypes`Fifth",
     "Prototypes`Sixth",
     "Prototypes`Seventh",
     "Prototypes`Eighth",
     "Prototypes`Ninth",
     "Prototypes`Tenth",
     "Prototypes`NextToLast",
     "Prototypes`Ultimate",
     "Prototypes`Penultimate",
     "Prototypes`Antepenultimate",
     "Prototypes`ElapsedTime"
     },
     Context -> {"Prototypes`"} }
  }
]
