Paclet[
  Name -> "Prototypes",
  Description -> "A paclet for prototype functions",
  Creator -> "Arnoud Buzing",
  Publisher -> "Wolfram Research",
  Version -> "0.3.4",
  MathematicaVersion -> "11.2+",
  Loading -> Automatic,
  Thumbnail -> "icons/icon.png",
  Extensions -> {
   { "Documentation", MainPage -> "Guides/Prototypes", Language -> "English"},
   { "Kernel",
   Symbols ->{"Prototypes`AlphaChannelQ", "Prototypes`Antepenultimate",
"Prototypes`BoxSyntaxQ", "Prototypes`BuildInfo",
"Prototypes`BuildWikiDocumentation", "Prototypes`By",
"Prototypes`CapitalizeSentences", "Prototypes`ClickToCopy",
"Prototypes`CommonestBy", "Prototypes`CopyAsBitmap",
"Prototypes`CreateDock", "Prototypes`CreateDockButton",
"Prototypes`CreateGIFAnimation", "Prototypes`CreateNotebookIndex",
"Prototypes`DatasetImport", "Prototypes`DatasetImportFiles",
"Prototypes`DatasetMap", "Prototypes`DeletePersistentObjects",
"Prototypes`DirectoryByteCount", "Prototypes`DirectoryFileList",
"Prototypes`DirectorySize", "Prototypes`DockButton",
"Prototypes`DockButton", "Prototypes`Eighth",
"Prototypes`ElapsedTime", "Prototypes`EntityPropertiesDataset",
"Prototypes`Fifth", "Prototypes`FileTranslate",
"Prototypes`FormatDetect", "Prototypes`Fourth",
"Prototypes`GeoService", "Prototypes`GetFiles",
"Prototypes`Image3DCubeQ", "Prototypes`ImageCropResize",
"Prototypes`ImageLandscapeQ", "Prototypes`ImagePortraitQ",
"Prototypes`ImageSquareQ", "Prototypes`ImageStrictlyLandscapeQ",
"Prototypes`ImageStrictlyPortraitQ", "Prototypes`ImportDirectory",
"Prototypes`ImportFiles", "Prototypes`InformationDataset",
"Prototypes`MakeString", "Prototypes`MaxBy", "Prototypes`MeanBy",
"Prototypes`MedianBy", "Prototypes`MinBy", "Prototypes`NextToLast",
"Prototypes`Ninth", "Prototypes`NotebookTranslate",
"Prototypes`PacletInformationDataset", "Prototypes`Penultimate",
"Prototypes`QuickSearch", "Prototypes`RandomGeoPosition",
"Prototypes`Rarest", "Prototypes`RarestBy",
"Prototypes`ResourceObjectDataset",
"Prototypes`ResourceObjectManager", "Prototypes`RGBColor255",
"Prototypes`Second", "Prototypes`Seventh", "Prototypes`Sixth",
"Prototypes`StandardDeviationBy", "Prototypes`StringFirst",
"Prototypes`StringLast", "Prototypes`StringMost",
"Prototypes`StringRest", "Prototypes`SystemStringOpen",
"Prototypes`Tenth", "Prototypes`Third",
"Prototypes`ToStringFileName", "Prototypes`TranslationCell",
"Prototypes`Ultimate", "Prototypes`Uniconize", "Prototypes`UnmatchQ",
"Prototypes`URLHash", "Prototypes`VarianceBy",
"Prototypes`WolframBeta", "Prototypes`$AppDataDirectory",
"Prototypes`$BuildInfo", "Prototypes`$DockButtons",
"Prototypes`$DockButtons", "Prototypes`$ExtensionToFormat",
"Prototypes`$FormatToExtension", "Prototypes`$InputDirectoryName",
"Prototypes`$LocalAppDataDirectory",
"Prototypes`$LocalResourceObjects",
"Prototypes`$RoamingAppDataDirectory",
"Prototypes`$UUIDStringPattern", "Prototypes`LayeredGeoGraphics",
"Prototypes`RenderOnlineNotebook","Prototypes`CreateNotebookRenderAPI",
"Prototypes`CaptureFromIPCamera","Prototypes`Prototype", "Prototypes`FilePartition", "Prototypes`FileJoin",
"Prototypes`FilePattern", "Prototypes`StringSwap","Prototypes`Antonyms","Prototypes`Synonyms",
"Prototypes`NounQ", "Prototypes`VerbQ", "Prototypes`AdjectiveQ",
"Prototypes`AdverbQ", "Prototypes`StringComplement", "Prototypes`StringIntersection", "Prototypes`StringUnion"},
     Context -> {"Prototypes`"} }
  }
]
