Paclet[
  Name -> "Prototypes",
  Description -> "A paclet for prototype functions",
  Creator -> "Arnoud Buzing",
  Publisher -> "Wolfram Research",
  Version -> "0.0.5",
  MathematicaVersion -> "11.2+",
  Loading -> Automatic,
  Extensions -> {
   { "Documentation", Language -> "English"},
   { "Kernel",
   Symbols -> {
     "Prototypes`InformationDataset",
     "Prototypes`ImportFiles",
     "Prototypes`ImportDirectory",
     "Prototypes`GetFiles",
     "Prototypes`DirectoryByteCount",
     "Prototypes`DirectorySize",
     "Prototypes`ToStringFileName",
     "Prototypes`URLHash",
     "Prototypes`$InputDirectoryName",
     "Prototypes`$ExtensionToFormat",
     "Prototypes`$FormatToExtension",
     "Prototypes`SystemStringOpen",
     "Prototypes`By",
     "Prototypes`MeanBy",
     "Prototypes`StandardDeviationBy",
     "Prototypes`MedianBy",
     "Prototypes`VarianceBy",
     "Prototypes`CommonestBy",
     "Prototypes`MinBy",
     "Prototypes`MaxBy",
     "Prototypes`RarestBy",
     "Prototypes`Rarest",
     "Prototypes`DatasetMap",
     "Prototypes`DatasetImport",
     "Prototypes`DatasetImportFiles",
     "Prototypes`StringRest",
     "Prototypes`StringMost",
     "Prototypes`RandomGeoPosition",
     "Prototypes`ImageStrictlyPortraitQ",
     "Prototypes`ImagePortraitQ",
     "Prototypes`ImageStrictlyLandscapeQ",
     "Prototypes`ImageLandscapeQ",
     "Prototypes`ImageSquareQ",
     "Prototypes`Image3DCubeQ",
     "Prototypes`ImageCropResize",
     "Prototypes`AlphaChannelQ",
     "Prototypes`Uniconize",
     "Prototypes`PacletInformationDataset",
     "Prototypes`BuildWikiDocumentation",
     "Prototypes`BuildInfo"
     },
     Context -> {"Prototypes`"} }
  }
]
